### ISSUE TITLE
fix light chain

### ISSUE THREAD

**Issue by psathyrella** [matsengrp/linearham#83]
At least on my last pull, it was crashing when it was parsing the linearham annotation, but unfortunately I can't find the err logs atm. But if someone is working on this and can't replicate it just lmk. Here's a light chain file for testing: https://github.com/psathyrella/partis/blob/dev/test/paired/ref-results/partition-new-simu/partition-igk.yaml

**Comment by psathyrella** [comment]
ok! i think i have tracked this down. To replicate (rename yaml since github won't let me upload yaml):

`./scripts/write_lh_annotations.py cluster.yaml linearham_run.log --output-base path/to/out`

[linearham_run.log](https://github.com/matsengrp/linearham/files/7836465/linearham_run.log)
[cluster_yaml.log](https://github.com/matsengrp/linearham/files/7836466/cluster_yaml.log)

issue seems to be that linearham doesn't write the actual VJ insertion for light chain insertions (like it does for heavy insertions), instead just writes a boolean if it's there:
![heavy](https://user-images.githubusercontent.com/2960243/148710792-287c40c8-e93d-4458-8035-5481015d4b41.png)
![light](https://user-images.githubusercontent.com/2960243/148710801-4b21ebe8-652f-4700-9429-817337291745.png)

which means that this line fails: https://github.com/matsengrp/linearham/blob/master/scripts/write_lh_annotations.py#L59
because it's resetting the deletion length without changing the insertion length:

```        Traceback (most recent call last):
          File "./scripts/write_lh_annotations.py", line 61, in update_partis_line_with_lh_annotation
            utils.add_implicit_info(glfo, partis_line, check_line_keys=debug)
          File "/home/dralph/work/linearham/lib/partis/python/utils.py", line 1711, in add_implicit_info
            raise Exception('naive and mature sequences different lengths %d %d for %s:\n    %s\n    %s' % (len(line['naive_seq']), len(line['seqs'][iseq]), ' '.join(line['unique_ids']), line['naive_seq'], line['seqs'][iseq]))
        Exception: naive and mature sequences different lengths 321 322 for 0901808538749971629-igk 5827556154176009883-igk 0316148055258110569-igk 0673794353012672613-igk 5234516726189794955-igk:
            GACATCCAGATGACCCAGTCTCCATCTTCTGTGTCTGCATCTGTAGGAGACAGAGTCACCATCACTTGTCGGGCGAGTCAGGGTATTAGCAGCTGGTTAGCCTGGTATCAGCAGAAACCAGGGAAAGCCCCTAAGCTCCTGATCTATGCTGCATCCAGTTTGCAAAGTGGGGTCCCATCAAGGTTCAGCGGCAGTGGATCTGGGACAGATTTCACTCTCACTATCAGCAGCCTGCAGCCTGAAGATTTTGCAACTTACTATTGTCAACAGGCTAACAGTTTCCCTGCACTTTTGGCCAGGGGACCAAGCTGGAGATCAAAC                                                                                                                                                                                   
            GACATCCAAATAACCCAGTCTCCATCTTCTGCGTCTCCATCTGGAGTCGACAGAGTCACCATCACTTCTCGGGCTAGTCAGGGCATTAGCAGCTGGTTAGCTTGGTATCAGCAGCAGCCAGGGCAAGCCCCTAAGCTCCTGTTCTATGCTGCATGCAGTTTGCAAAGTGGAGTCCCATCAAGGTTCAGCGGCCGTGGATCTGGGACAGATTTCACTCTCACTATCAGCAGCCTGCCGCCTGAAAATTTTGTACCTTACTATTGTCAACAGGCTAACAGGTTCCCTTGCCCTTTTGGCTAGGGGACAAATCTGGAGATCATTC                                                                                                                                                                                  

```

**Comment by psathyrella** [comment]
This seems to be written by this line: https://github.com/matsengrp/linearham/blob/master/src/PhyloHMM.cpp#L320

but I can't figure out how the value of `vd_junction_insertion_samp_` gets set.

**Comment by psathyrella** [comment]
Well [this](https://github.com/psathyrella/partis/commit/13362520ab602a3af67d6b3502ebfef3da83b48b) (and [this](https://github.com/psathyrella/partis/commit/28a86eaeeeea1383b93541c0c38480f75e0f24d6)) get around the issue by looking for TRUE valued VJ insertion and figuring out what it's supposed to be, but it would be a lot better to figure out why linearham is writing the TRUE to begin with.

**Comment by colejensen** [comment]
Has this issue been resolved with the current Docker image? I am running into the same problems being described there with light chains. I've attached an example that shows the error is still occurring. 

[vquest.xls](https://github.com/user-attachments/files/22349379/vquest.xls)
[error.txt](https://github.com/user-attachments/files/22349378/error.txt)
[all_samples_airr.txt](https://github.com/user-attachments/files/22349380/all_samples_airr.txt)

**Comment by psathyrella** [comment]
Unfortunately no, I don't think so, we haven't had a chance to look at linearham in quite a while. But I think you should be able to avoid it by calling the partis function linked in the previous message (Jan 10 2022):

https://github.com/psathyrella/partis/commit/13362520ab602a3af67d6b3502ebfef3da83b48b
https://github.com/psathyrella/partis/commit/28a86eaeeeea1383b93541c0c38480f75e0f24d6

partis is pip installable now so hopefully that shouldn't bee too difficult.

**Comment by psathyrella** [comment]
Adding some detail for posterity here on running the fix mentioned above (Jan 10 2022 message). You should just need to run [scripts/write_lh_annotations.py](https://github.com/matsengrp/linearham/blob/main/scripts/write_lh_annotations.py) with a partis yaml file and linearham log file as input. For more info see that script's `--help` and the [manual](https://github.com/matsengrp/linearham?tab=readme-ov-file#run-steps). That script calls the `fix_linearham_insertion()` function from partis. I unfortunately don't have any linearham outputs lying around to run it quickly, but please let me know if you run into any trouble.
